##
## PaperplaneRemix - A modular Telegram selfbot script
## Copyright (C) 2022, Avinash Reddy and the PaperplaneRemix contributors
##
## SPDX-License-Identifier: GPL-3.0-or-later
##
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v4.2.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-ast
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'v1.0'
    hooks:
      - id: upgrade-type-hints
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.5
    hooks:
      - id: ssort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
          - flake8-quotes
          - flake8-async
        args:
          - '--ignore=W503,Q003,E203'
          - '--max-line-length=120'
          - '--inline-quotes=double'
          - '--per-file-ignores=
              userbot/__main__.py:T001
              userbot/__init__.py:T001
              generate_session.py:T001'
  - repo: 'https://github.com/johann-petrak/licenseheaders'
    rev: 'v0.8.8'
    hooks:
      - id: licenseheaders
        args: ["-t", ".copyright.tmpl", "-cy", "-x", "userbot/utils/FastTelethon.py", "-f"]
